name: Build and Deploy

on:
    - push
    - pull_request

jobs:
    job1:
        env:
            DB_URL: ${{secrets.DB_URL}}
            PG_USER: ${{secrets.PG_USER}}
            PG_PASS: ${{secrets.PG_PASS}}
            PG_DB: ${{secrets.PG_DB}}

        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: ${{secrets.PG_USER}}
                    POSTGRES_PASSWORD: ${{secrets.PG_PASS}}
                    POSTGRES_DB: ${{secrets.PG_DB}}
                ports:
                    - 5432:5432

        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: instalando o python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12.1"
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: instalar dependencias
              run: pip install -r requirements.txt
            - name: Esperando o PostgreSQL ficar pronto
              run: sleep 15
            - name: test
              run: echo ${{secrets.DB_URL}}
            - name: Executar pytest
              env:
                  DATABASE_URL: ${{secrets.DB_URL}}
              run: pytest teste.py
